---
version: '3.7'
services:
  python-boltons.typist:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/typist:delegated
    working_dir: /typist
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
